baseURL = "/"
languageCode = "en-us"
title = "Kominote Riral Teknoloji - KoRiTek"
description = "A non-profit organization focusing on technology development in Haiti."
theme = "koritek"

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Projects"    
    url  = "/projects/"
    weight = 3

[[menu.main]]
    name = "Photos"
    url  = "/photos/"
    weight = 4    

[[menu.main]]
    name = "Get Involved"
    url  = "/volunteer/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6    
