[context.production.environment]
  HUGO_VERSION = "0.43"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.43"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.43"