[context.production.environment]
  HUGO_VERSION = "0.36.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.36.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.36.1"