---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/directors
  label: Directors
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: document
  path: config.toml
  label: Config
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.46'
